
// Below are some example sentences for user to try
// Generated by AI(of course!)
export const exampleSentences = [
    "The new parking fines are positively draconian.",
    "She had a penchant for exotic foods.",
    "The weather today is quite unpredictable.",
    "He was known for his philanthropic efforts.",
    "The architecture of the building is stunning.",
    "Her eloquence in speech was admired by all.",
    "The book offers profound insights into human nature.",
    "He faced the challenge with unwavering determination.",
    "The festival was a vibrant celebration of culture.",
    "She navigated the complex situation with grace.",
    "The artist's work is a blend of modern and traditional styles.",
    "He has an innate ability to solve problems.",
    "The movie's plot was both intriguing and thought-provoking.",
    "She has a meticulous approach to her work.",
    "The landscape was dotted with picturesque cottages.",
    "He was an advocate for environmental conservation.",
    "The team's synergy was evident in their performance.",
    "She has a keen eye for detail.",
    "The lecture was both informative and engaging.",
    "He was a pioneer in his field."
]

// Tokenize the text into words and delimiters, so that user can select words manually.
export function tokenizeText(text: string) {
    const tokens = []
    let currentToken = ''
    let currentType = ''

    for (let i = 0; i < text.length; i++) {
        const char = text[i]
        if (/[a-zA-Z-]/.test(char)) {
            if (currentType !== 'word') {
                if (currentToken) tokens.push({ type: currentType, value: currentToken })
                currentToken = char
                currentType = 'word'
            } else {
                currentToken += char
            }
        } else {
            if (currentType !== 'delimiter') {
                if (currentToken) tokens.push({ type: currentType, value: currentToken })
                currentToken = char
                currentType = 'delimiter'
            } else {
                currentToken += char
            }
        }
    }

    if (currentToken) tokens.push({ type: currentType, value: currentToken })
    return tokens
}
